---
- name: Build Docker Image
  hosts: docker_host
  become: yes

  vars:
    docker_image_tags:
      - "{{ build_number_tag }}"
      - "latest"

  tasks:
    - name: Install Docker package
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Install git package
      yum:
        name: git
        state: present

    - name: Clone repository
      git:
        repo: "https://github.com/M95kandan/end-to-end-CI-CD.git"
        dest: "/home/ec2-user/end-to-end-CI-CD"
        clone: yes

    - name: Change directory to cloned repository
      become: yes
      become_user: ec2-user
      shell: cd /home/ec2-user/end-to-end-CI-CD

    - name: Build and tag Docker image
      command: "docker build -t {{ dockerhub_repository }}:{{ item }} /home/ec2-user/end-to-end-CI-CD"
      become: yes
      loop: "{{ docker_image_tags }}"
